"""user_id for analog

Revision ID: 78d39eb31181
Revises: 8b55ff4e4b3e
Create Date: 2026-09-04 23:55:09.876849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d39eb31181'
down_revision: Union[str, Sequence[str], None] = '8b55ff4e4b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###
