// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 172);
user_pref("browser.newtabpage.activity-stream.impressionId", "{019a8fba-056d-4b32-810d-7b898c539599}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "never");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\",\"webcompat@mozilla.org\",\"screenshots@mozilla.org\",\"pictureinpicture@mozilla.org\",\"formautofill@mozilla.org\"]");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20260831224046");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.lastColdStartupCheck", 1789496857);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\",\"new-tab-button\",\"alltabs-button\",\"personal-bookmarks\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\"],\"vertical-tabs\":[],\"PersonalToolbar\":[]},\"seen\":[\"reset-pbm-toolbar-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"TabsToolbar\",\"vertical-tabs\",\"PersonalToolbar\",\"toolbar-menubar\"],\"currentVersion\":24,\"newElementCount\":2}");
user_pref("captchadetection.lastSubmission", 1789404);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "b0bacafe-b0ba-cafe-b0ba-cafeb0bacafe");
user_pref("datareporting.dau.cachedUsageProfileID", "beefbeef-beef-beef-beef-beeefbeefbee");
user_pref("distribution.iniFile.exists.appversion", "152.0.4-beta.30");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.filesystem.pathcheck.disabled", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20260831224046");
user_pref("extensions.lastAppVersion", "152.0.4-beta.30");
user_pref("extensions.lastPlatformVersion", "152.0.4");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"531e7aa3-c7e8-46e1-ab1f-3b39a2cfb596\",\"formautofill@mozilla.org\":\"bbb8b921-4218-4e46-869b-bbbbec65739a\",\"ipp-activator@mozilla.com\":\"77ef3f77-1160-4e26-8e61-9074f696ad06\",\"pictureinpicture@mozilla.org\":\"b3ecb4a6-d1d9-4f85-8aee-1c9e53bfa628\",\"addons-search-detection@mozilla.com\":\"8f3256be-51c1-4332-a245-d8cefab3e4a6\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"3a6544ec-b02f-4747-bb1c-41914d9311e5\",\"firefox-compact-dark@mozilla.org\":\"d7035de3-999e-44ba-bf18-e446984c25cb\",\"uBlock0@raymondhill.net\":\"805919d8-2ea1-4d3b-944c-317fb06611b0\"}");
user_pref("font.system.whitelist", "Arial,Calibri,Cambria Math,Consolas,Courier New,Georgia,Nirmala UI,Segoe UI,Tahoma,Times New Roman,Trebuchet MS,Verdana,游ゴシック Light,Twemoji Mozilla,MV Boli,SimSun-ExtB,Segoe Fluent Icons,Constantia,Microsoft Yi Baiti,Yu Gothic UI Semibold,맑은 고딕,Lucida Sans Unicode,Microsoft YaHei Light,微软雅黑 Light,NSimSun,ＭＳ ゴシック,SimSun,Segoe UI Light,Comic Sans MS,Marlett,Lucida Console,微軟正黑體 Light,Microsoft YaHei UI,Gabriola,Segoe UI Variable,Ink Free,宋体,ＭＳ Ｐゴシック,Yu Gothic Medium,Corbel Light,Microsoft JhengHei Light,微軟正黑體,Segoe UI Black,Sitka,Wingdings,Segoe Script,Symbol,Gadugi,MS UI Gothic,Myanmar Text,Microsoft Sans Serif,微软雅黑,Microsoft YaHei UI Light,Segoe UI Historic,新細明體-ExtB,MingLiU_HKSCS-ExtB,Palatino Linotype,Microsoft YaHei,Bahnschrift,Mongolian Baiti,Microsoft JhengHei UI,Impact,Javanese Text,Malgun Gothic Semilight,Sylfaen,Ebrima,Segoe UI Emoji,Yu Gothic Light,Leelawadee UI Semilight,Segoe UI Semilight,MS PGothic,細明體-ExtB,游ゴシック Medium,Microsoft New Tai Lue,Segoe MDL2 Assets,Arial Black,MingLiU-ExtB,Webdings,Microsoft JhengHei UI Light,Microsoft Tai Le,Leelawadee UI,HoloLens MDL2 Assets,MS Gothic,Malgun Gothic,Calibri Light");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("intl.accept_languages", "ru-RU, ru");
user_pref("media.getdisplaymedia.screencapturekit.enabled", false);
user_pref("media.getdisplaymedia.screencapturekit.picker.enabled", false);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("network.dns.disableIPv6", true);
user_pref("nimbus.profileId", "08d81d29-f6dd-4afd-a11f-bbe6d24bfbad");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("roverfox.s.timezone_0", "Asia/Novosibirsk");
user_pref("security.sandbox.warn_unprivileged_namespaces", false);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.profiles.storeID", "d2972658");
user_pref("toolkit.startup.last_success", 1789496856);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.cachedProfileGroupID", "decafdec-afde-cafd-ecaf-decafdecafde");
user_pref("toolkit.telemetry.previousBuildID", "20260831224046");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("webgl.force-enabled", true);
